steps:
  # 0. Copy environment file
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", ".env"]
    dir: "be"

  # 0.5. Verify environment file
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "=== Checking environment file ==="
        if [ -f .env ]; then
          echo "✅ .env file exists"
          echo "Environment variables (hiding sensitive data):"
          sed 's/=.*/=[HIDDEN]/' .env
        else
          echo "❌ .env file not found"
          exit 1
        fi
    dir: "be"

  # 1. Build Docker image untuk backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/bahasa-app-backend", "."]
    dir: "be"

  # 2. Push ke Container Registry / Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/bahasa-app-backend"]

  # 2.5. Test database connection and run migrations
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "=== Testing database connection ==="
        docker run --rm \
        --env-file .env \
        gcr.io/$PROJECT_ID/bahasa-app-backend \
        npm run db:check
        
        echo "=== Creating database if needed ==="
        docker run --rm \
        --env-file .env \
        gcr.io/$PROJECT_ID/bahasa-app-backend \
        npm run db:create || echo "Database might already exist, continuing..."
        
        echo "=== Running database migrations ==="
        docker run --rm \
        --env-file .env \
        gcr.io/$PROJECT_ID/bahasa-app-backend \
        npm run db:migrate
    dir: "be"

  # 3. Deploy ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "bahasa-app-backend",
        "--image",
        "gcr.io/$PROJECT_ID/bahasa-app-backend",
        "--timeout",
        "1000s",
        "--port",
        "3000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

# Log hanya akan disimpan di Google Cloud Logging
# Log tidak akan disimpan di Google Cloud Storage (butuh hak akses).
options:
  logging: CLOUD_LOGGING_ONLY